name: Terraform Apply (Main)

on:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      dev: ${{ steps.filter.outputs.dev }}
      stage: ${{ steps.filter.outputs.stage }}
      prod: ${{ steps.filter.outputs.prod }}
      modules: ${{ steps.filter.outputs.modules }}
      bootstrap: ${{ steps.filter.outputs.bootstrap }}

    steps:
      - uses: actions/checkout@v4

      - name: Detect changed paths
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            dev:
              - 'envs/dev/**'
            stage:
              - 'envs/stage/**'
            prod:
              - 'envs/prod/**'
            modules:
              - 'modules/**'
            bootstrap:
              - 'bootstrap/github-actions/**'

# EKS INFRA
  eks-infra:
    needs: detect-changes
    if: |
      needs.detect-changes.outputs.dev == 'true' ||
      needs.detect-changes.outputs.modules == 'true' ||
      needs.detect-changes.outputs.bootstrap == 'true'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN_DEV }}
          aws-region: us-east-1

      - uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: envs/dev/01_eks_infra
        run: |
          terraform init \
            -backend-config=../global/backend.hcl \
            -backend-config="key=dev/eks-infra.tfstate"

      - name: Terraform Apply
        working-directory: envs/dev/01_eks_infra
        run: terraform apply -var-file=dev.tfvars -auto-approve

  eks-access:
    needs: eks-infra
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN_DEV }}
          aws-region: us-east-1

      - uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: envs/dev/03_argocd
        run: |
          terraform init \
            -backend-config=../global/backend.hcl \
            -backend-config="key=dev/argocd.tfstate"

      - name: Terraform Apply
        working-directory: envs/dev/03_argocd
        run: terraform apply -var-file=dev.tfvars -auto-approve